name: myworkflow

on:

  push:
    branches: main

  pull_request:
    branches: main

jobs:
  docker-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: build services
        run: docker compose build

      - name: run services
        run: docker compose up -d

      - name: show containers
        run: docker compose ps

      - name: stop services
        run: docker compose down


        




        



        







      
  
