name: backend

on:

  push:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - name: Checkout front-end repo
        uses: actions/checkout@v4
        with:
          path: frontend
        
      - name: Checkout back-end repo
        uses: actions/checkout@v4
        with:
          repository: Bashar-OP/CI_CD_Back
          path: backend
          
      - name: Run runner docker compose
        run: |
          docker-compose up -d
          docker-compose down




        



        







      
  
