name: backend
   
on:
  push:
    branches: [ main ] 

jobs:
  docker-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout back-end repo
        uses: actions/checkout@v4
        with:
          path: backend
        
      - name: Checkout front-end repo
        uses: actions/checkout@v4
        with:
          repository: Bashar-OP/CI_CD-Front
          path:  frontend

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build Backend image
        run: |
           cd backend
           docker build -t ghcr.io/${OWNER_LC}/backend:latest .
           cd ..

      - name: Push Backend image
        run: docker push ghcr.io/${OWNER_LC}/backend:latest
        
      - name: Build Frontend image
        run: |
           cd frontend
           docker build -t ghcr.io/${OWNER_LC}/frontend:latest .
           cd ..

      - name: Push Frontend image
        run: docker push ghcr.io/${OWNER_LC}/frontend:latest

      




        



        







      
  
